### PR TITLE
Change the behaviour of the enter key in the picker

### PR DESCRIPTION
**Pull request by iainh**
Currently when selecting a file with the arrow keys in the picker and pressing
enter the file name is not added to the path resulting in the following error
being reported:
```
  Could not open file: Is a directory (os error 21)
```
Similarly, selecting a directory and pressing enter results in the same error
being displayed.

This commit changes the behaviour when enter is pressed to the following:

1.  If a file is selected, open it

2.  f a directory is selected, navigate into it and refresh the picker view

 Compared to the stock Emacs behaviours, the file selected case now matches but
 the directory selected case should result in the directory contents being
 displayed in the buffer. Zee doesn't current support this functionality but
 when/if it does this portion of the patch could change.

### CODE REVIEW

**Comment by mcobzarenco** [comment]
Thanks for the PR and sorry for slow reply! (I mentioned on the other PRs too). 

I agree the current behaviour can be unexpected and that it doesn't match standard emacs. It's something I attempted to fix with how `find-file` works in emacs for existing vs new files. Currently, in the file picker
 - `RET` opens a file with that name if it exists or otherwise it creates a new file.
 - `TAB` autocompletes the currently selected path -- so `TAB` followed by `RET` would open a file

This treats existing and new files uniformly. But, the typical behaviour of selecting items in a list and pressing `RET`1 is that the selected item is selected. So yeah, it's pretty counter-intuitive.

I'm not sure if it's still possible to create a new file with your changes?

**Comment by iainh** [comment]
File creation was a case I missing in this PR. I've updated it now to handle that case and confirmed that the behaviour matches emacs. That is: enter when a file is selected opens it while enter creates the file when the filename does not exist.

There is what appears to me a bug where you can't create a file who's name is a substring of an existing one in the same directory (e.g. creating a file with name `zee` in a directory containing `zee.log`) but Zee prior to this change and Emacs both exhibit the same behaviour so it probably isn't an issue.

**Comment by mcobzarenco** [comment]
> There is what appears to me a bug where you can't create a file who's name is a substring of an existing one in the same directory (e.g. creating a file with name zee in a directory containing zee.log) but Zee prior to this change and Emacs both exhibit the same behaviour so it probably isn't an issue.

My apologies, I wasn't very clear. This is precisely the case I am referring to and what I tried to improve upon compared to standard Emacs. Currently, it *is* possible to create a file whose name is a substring of an existing one currently existing one by just pressing `RET`, i.e.

> -  RET opens a file with that name if it exists or **otherwise it creates a new file**.
> -  TAB autocompletes the currently selected path -- so TAB followed by RET would open a file

Emacs also has a solution for this, you can move out of the list and select the search input:
Peek 2022-07-18 23-37

---

Disallowing creating files with substring names is clearly not acceptable, although the current behaviour could be improved on. Maybe the Emacs solution is better

**Comment by iainh** [comment]
Closing this pull request for now. Time allowing I'll rework it in the future.

**Pull request closed without merging**
